"""
nuevo_cambio

Revision ID: 055bc340cf1d
Revises: '892afa9e3fc5'
Create Date: 2026-02-06 18:30:50.784112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '055bc340cf1d'
down_revision: Union[str, None] = '892afa9e3fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('uq_webhook_instance_topic_url', table_name='webhook_config')
    op.alter_column('woocommerce_instances', 'product_descriptions',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('woocommerce_instances', 'product_descriptions',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)
    op.create_index('uq_webhook_instance_topic_url', 'webhook_config', ['instance_id', 'topic', 'delivery_url'], unique=True)
    # ### end Alembic commands ###
