"""
remove_partida_posicion_unique_constraint

Revision ID: 0a6ce49d12b1
Revises: 'e8ebc767d0f7'
Create Date: 2026-03-12 15:45:38.822748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6ce49d12b1'
down_revision: Union[str, None] = 'e8ebc767d0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('odoo_name', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('product_tpl_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('needs_sync', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error_details', sa.String(length=500), nullable=True),
    sa.Column('wc_date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wc_date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odoo_write_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_tpl_id'], ['product_sync.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variant_sync_error_details'), 'product_variant_sync', ['error_details'], unique=False)
    op.create_index(op.f('ix_product_variant_sync_id'), 'product_variant_sync', ['id'], unique=False)
    op.create_index(op.f('ix_product_variant_sync_instance_id'), 'product_variant_sync', ['instance_id'], unique=False)
    op.create_index(op.f('ix_product_variant_sync_message'), 'product_variant_sync', ['message'], unique=False)
    op.create_index(op.f('ix_product_variant_sync_odoo_id'), 'product_variant_sync', ['odoo_id'], unique=False)
    op.create_index(op.f('ix_product_variant_sync_odoo_name'), 'product_variant_sync', ['odoo_name'], unique=False)
    op.create_index(op.f('ix_product_variant_sync_product_tpl_id'), 'product_variant_sync', ['product_tpl_id'], unique=False)
    op.create_index(op.f('ix_product_variant_sync_woocommerce_id'), 'product_variant_sync', ['woocommerce_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variant_sync_woocommerce_id'), table_name='product_variant_sync')
    op.drop_index(op.f('ix_product_variant_sync_product_tpl_id'), table_name='product_variant_sync')
    op.drop_index(op.f('ix_product_variant_sync_odoo_name'), table_name='product_variant_sync')
    op.drop_index(op.f('ix_product_variant_sync_odoo_id'), table_name='product_variant_sync')
    op.drop_index(op.f('ix_product_variant_sync_message'), table_name='product_variant_sync')
    op.drop_index(op.f('ix_product_variant_sync_instance_id'), table_name='product_variant_sync')
    op.drop_index(op.f('ix_product_variant_sync_id'), table_name='product_variant_sync')
    op.drop_index(op.f('ix_product_variant_sync_error_details'), table_name='product_variant_sync')
    op.drop_table('product_variant_sync')
    # ### end Alembic commands ###
