"""
add attribute sync tables

Revision ID: 14400774b44c
Revises: '006'
Create Date: 2026-01-18 21:45:20.398575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14400774b44c'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_description'), 'admins', ['description'], unique=False)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_name'), 'admins', ['name'], unique=False)
    op.create_table('attribute_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('odoo_attribute_id', sa.Integer(), nullable=False),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('woo_type', sa.String(length=50), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('need_update', sa.Boolean(), nullable=True),
    sa.Column('is_mapped', sa.Boolean(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.Column('last_exported_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_syncs_id'), 'attribute_syncs', ['id'], unique=False)
    op.create_index(op.f('ix_attribute_syncs_odoo_attribute_id'), 'attribute_syncs', ['odoo_attribute_id'], unique=False)
    op.create_index(op.f('ix_attribute_syncs_woocommerce_id'), 'attribute_syncs', ['woocommerce_id'], unique=False)
    op.create_table('attribute_value_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('odoo_value_id', sa.Integer(), nullable=False),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('woocommerce_attribute_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('need_update', sa.Boolean(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.Column('last_exported_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_value_syncs_id'), 'attribute_value_syncs', ['id'], unique=False)
    op.create_index(op.f('ix_attribute_value_syncs_odoo_value_id'), 'attribute_value_syncs', ['odoo_value_id'], unique=False)
    op.create_index(op.f('ix_attribute_value_syncs_woocommerce_id'), 'attribute_value_syncs', ['woocommerce_id'], unique=False)
    op.create_index(op.f('ix_category_sync_id'), 'category_sync', ['id'], unique=False)
    op.drop_constraint('fk_category_sync_instance_id', 'category_sync', type_='foreignkey')
    op.create_foreign_key(None, 'category_sync', 'woocommerce_instances', ['instance_id'], ['id'])
    op.create_index(op.f('ix_celery_task_logs_id'), 'celery_task_logs', ['id'], unique=False)
    op.drop_constraint('fk_celery_task_logs_instance_id', 'celery_task_logs', type_='foreignkey')
    op.create_foreign_key(None, 'celery_task_logs', 'woocommerce_instances', ['instance_id'], ['id'])
    op.create_index(op.f('ix_product_sync_id'), 'product_sync', ['id'], unique=False)
    op.drop_constraint('fk_product_sync_instance_id', 'product_sync', type_='foreignkey')
    op.create_foreign_key(None, 'product_sync', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_constraint('fk_tag_sync_instance_id', 'tag_sync', type_='foreignkey')
    op.create_foreign_key(None, 'tag_sync', 'woocommerce_instances', ['instance_id'], ['id'])
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.drop_constraint('fk_webhook_logs_instance_id', 'webhook_logs', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_logs', 'woocommerce_instances', ['instance_id'], ['id'])
    op.alter_column('woocommerce_instances', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_woocommerce_instances_id'), 'woocommerce_instances', ['id'], unique=False)
    op.drop_constraint('fk_woocommerce_instances_user_id', 'woocommerce_instances', type_='foreignkey')
    op.create_foreign_key(None, 'woocommerce_instances', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'woocommerce_instances', type_='foreignkey')
    op.create_foreign_key('fk_woocommerce_instances_user_id', 'woocommerce_instances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_woocommerce_instances_id'), table_name='woocommerce_instances')
    op.alter_column('woocommerce_instances', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'webhook_logs', type_='foreignkey')
    op.create_foreign_key('fk_webhook_logs_instance_id', 'webhook_logs', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_constraint(None, 'tag_sync', type_='foreignkey')
    op.create_foreign_key('fk_tag_sync_instance_id', 'tag_sync', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_sync', type_='foreignkey')
    op.create_foreign_key('fk_product_sync_instance_id', 'product_sync', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_sync_id'), table_name='product_sync')
    op.drop_constraint(None, 'celery_task_logs', type_='foreignkey')
    op.create_foreign_key('fk_celery_task_logs_instance_id', 'celery_task_logs', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_celery_task_logs_id'), table_name='celery_task_logs')
    op.drop_constraint(None, 'category_sync', type_='foreignkey')
    op.create_foreign_key('fk_category_sync_instance_id', 'category_sync', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_category_sync_id'), table_name='category_sync')
    op.drop_index(op.f('ix_attribute_value_syncs_woocommerce_id'), table_name='attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_value_syncs_odoo_value_id'), table_name='attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_value_syncs_id'), table_name='attribute_value_syncs')
    op.drop_table('attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_syncs_woocommerce_id'), table_name='attribute_syncs')
    op.drop_index(op.f('ix_attribute_syncs_odoo_attribute_id'), table_name='attribute_syncs')
    op.drop_index(op.f('ix_attribute_syncs_id'), table_name='attribute_syncs')
    op.drop_table('attribute_syncs')
    op.drop_index(op.f('ix_admins_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_description'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
