"""
add email to users

Revision ID: 28e4f56d186e
Revises: '007'
Create Date: 2026-01-21 21:31:17.220963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e4f56d186e'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sync', sa.Column('odoo_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_product_sync_odoo_name'), 'product_sync', ['odoo_name'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sync_odoo_name'), table_name='product_sync')
    op.drop_column('product_sync', 'odoo_name')
    # ### end Alembic commands ###
