"""
nuevo_cambio

Revision ID: 3c4e94de10eb
Revises: 'None'
Create Date: 2026-03-01 09:30:46.823679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4e94de10eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_description'), 'admins', ['description'], unique=False)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_name'), 'admins', ['name'], unique=False)
    op.create_table('client_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('woo_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_sync_id'), 'client_sync', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('woocommerce_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('woocommerce_url', sa.String(length=500), nullable=True),
    sa.Column('woocommerce_consumer_key', sa.String(length=255), nullable=True),
    sa.Column('woocommerce_consumer_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('odoo_url', sa.String(length=500), nullable=True),
    sa.Column('odoo_db', sa.String(length=255), nullable=True),
    sa.Column('odoo_username', sa.String(length=255), nullable=True),
    sa.Column('odoo_password', sa.String(length=255), nullable=True),
    sa.Column('auto_sync_products', sa.Boolean(), nullable=True),
    sa.Column('auto_sync_orders', sa.Boolean(), nullable=True),
    sa.Column('auto_sync_customers', sa.Boolean(), nullable=True),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odoo_language', sa.String(length=10), nullable=True),
    sa.Column('product_descriptions', sa.String(length=20), nullable=True),
    sa.Column('price_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_list_id'], ['pricelist_sync.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_woocommerce_instances_id'), 'woocommerce_instances', ['id'], unique=False)
    op.create_index(op.f('ix_woocommerce_instances_name'), 'woocommerce_instances', ['name'], unique=True)
    op.create_index(op.f('ix_woocommerce_instances_price_list_id'), 'woocommerce_instances', ['price_list_id'], unique=False)
    op.create_index(op.f('ix_woocommerce_instances_user_id'), 'woocommerce_instances', ['user_id'], unique=False)
    op.create_table('attribute_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('odoo_attribute_id', sa.Integer(), nullable=False),
    sa.Column('odoo_name', sa.String(length=255), nullable=True),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('woo_type', sa.String(length=50), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('need_update', sa.Boolean(), nullable=True),
    sa.Column('is_mapped', sa.Boolean(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.Column('last_exported_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_syncs_id'), 'attribute_syncs', ['id'], unique=False)
    op.create_index(op.f('ix_attribute_syncs_instance_id'), 'attribute_syncs', ['instance_id'], unique=False)
    op.create_index(op.f('ix_attribute_syncs_odoo_attribute_id'), 'attribute_syncs', ['odoo_attribute_id'], unique=False)
    op.create_index(op.f('ix_attribute_syncs_odoo_name'), 'attribute_syncs', ['odoo_name'], unique=False)
    op.create_index(op.f('ix_attribute_syncs_woocommerce_id'), 'attribute_syncs', ['woocommerce_id'], unique=False)
    op.create_table('attribute_value_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('odoo_value_id', sa.Integer(), nullable=False),
    sa.Column('odoo_name', sa.String(length=255), nullable=True),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('woocommerce_attribute_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('need_update', sa.Boolean(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.Column('last_exported_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_value_syncs_id'), 'attribute_value_syncs', ['id'], unique=False)
    op.create_index(op.f('ix_attribute_value_syncs_instance_id'), 'attribute_value_syncs', ['instance_id'], unique=False)
    op.create_index(op.f('ix_attribute_value_syncs_odoo_name'), 'attribute_value_syncs', ['odoo_name'], unique=False)
    op.create_index(op.f('ix_attribute_value_syncs_odoo_value_id'), 'attribute_value_syncs', ['odoo_value_id'], unique=False)
    op.create_index(op.f('ix_attribute_value_syncs_woocommerce_id'), 'attribute_value_syncs', ['woocommerce_id'], unique=False)
    op.create_table('category_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('odoo_name', sa.String(length=255), nullable=True),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('needs_sync', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error_details', sa.String(length=500), nullable=True),
    sa.Column('wc_date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wc_date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odoo_write_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_sync_error_details'), 'category_sync', ['error_details'], unique=False)
    op.create_index(op.f('ix_category_sync_id'), 'category_sync', ['id'], unique=False)
    op.create_index(op.f('ix_category_sync_instance_id'), 'category_sync', ['instance_id'], unique=False)
    op.create_index(op.f('ix_category_sync_message'), 'category_sync', ['message'], unique=False)
    op.create_index(op.f('ix_category_sync_odoo_id'), 'category_sync', ['odoo_id'], unique=False)
    op.create_index(op.f('ix_category_sync_odoo_name'), 'category_sync', ['odoo_name'], unique=False)
    op.create_index(op.f('ix_category_sync_woocommerce_id'), 'category_sync', ['woocommerce_id'], unique=False)
    op.create_table('celery_task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('parent_task_id', sa.String(length=255), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('task_args', sa.JSON(), nullable=True),
    sa.Column('task_kwargs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celery_task_logs_created_at'), 'celery_task_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_id'), 'celery_task_logs', ['id'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_instance_id'), 'celery_task_logs', ['instance_id'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_parent_task_id'), 'celery_task_logs', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_task_id'), 'celery_task_logs', ['task_id'], unique=True)
    op.create_index(op.f('ix_celery_task_logs_task_name'), 'celery_task_logs', ['task_name'], unique=False)
    op.create_table('product_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('odoo_name', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('needs_sync', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error_details', sa.String(length=500), nullable=True),
    sa.Column('wc_date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wc_date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odoo_write_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sync_error_details'), 'product_sync', ['error_details'], unique=False)
    op.create_index(op.f('ix_product_sync_id'), 'product_sync', ['id'], unique=False)
    op.create_index(op.f('ix_product_sync_instance_id'), 'product_sync', ['instance_id'], unique=False)
    op.create_index(op.f('ix_product_sync_message'), 'product_sync', ['message'], unique=False)
    op.create_index(op.f('ix_product_sync_odoo_id'), 'product_sync', ['odoo_id'], unique=False)
    op.create_index(op.f('ix_product_sync_odoo_name'), 'product_sync', ['odoo_name'], unique=False)
    op.create_index(op.f('ix_product_sync_woocommerce_id'), 'product_sync', ['woocommerce_id'], unique=False)
    op.create_table('tag_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('odoo_name', sa.String(length=255), nullable=True),
    sa.Column('woocommerce_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('needs_sync', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error_details', sa.String(length=500), nullable=True),
    sa.Column('wc_date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wc_date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odoo_write_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_sync_error_details'), 'tag_sync', ['error_details'], unique=False)
    op.create_index(op.f('ix_tag_sync_id'), 'tag_sync', ['id'], unique=False)
    op.create_index(op.f('ix_tag_sync_instance_id'), 'tag_sync', ['instance_id'], unique=False)
    op.create_index(op.f('ix_tag_sync_message'), 'tag_sync', ['message'], unique=False)
    op.create_index(op.f('ix_tag_sync_odoo_id'), 'tag_sync', ['odoo_id'], unique=False)
    op.create_index(op.f('ix_tag_sync_odoo_name'), 'tag_sync', ['odoo_name'], unique=False)
    op.create_index(op.f('ix_tag_sync_woocommerce_id'), 'tag_sync', ['woocommerce_id'], unique=False)
    op.create_table('webhook_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False, comment='e.g., product.created, order.updated'),
    sa.Column('delivery_url', sa.String(length=500), nullable=False, comment='URL where webhook payload is sent'),
    sa.Column('secret', sa.String(length=200), nullable=True, comment='Secret for webhook signature verification'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='Friendly name for webhook'),
    sa.Column('wc_webhook_id', sa.Integer(), nullable=True, comment='WooCommerce webhook ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active, paused, disabled'),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('api_version', sa.String(length=10), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_config_id'), 'webhook_config', ['id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['woocommerce_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_created_at'), 'webhook_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_event_id'), 'webhook_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_logs_event_type'), 'webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_instance_id'), 'webhook_logs', ['instance_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_payload_hash'), 'webhook_logs', ['payload_hash'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_payload_hash'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_instance_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_type'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_created_at'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_webhook_config_id'), table_name='webhook_config')
    op.drop_table('webhook_config')
    op.drop_index(op.f('ix_tag_sync_woocommerce_id'), table_name='tag_sync')
    op.drop_index(op.f('ix_tag_sync_odoo_name'), table_name='tag_sync')
    op.drop_index(op.f('ix_tag_sync_odoo_id'), table_name='tag_sync')
    op.drop_index(op.f('ix_tag_sync_message'), table_name='tag_sync')
    op.drop_index(op.f('ix_tag_sync_instance_id'), table_name='tag_sync')
    op.drop_index(op.f('ix_tag_sync_id'), table_name='tag_sync')
    op.drop_index(op.f('ix_tag_sync_error_details'), table_name='tag_sync')
    op.drop_table('tag_sync')
    op.drop_index(op.f('ix_product_sync_woocommerce_id'), table_name='product_sync')
    op.drop_index(op.f('ix_product_sync_odoo_name'), table_name='product_sync')
    op.drop_index(op.f('ix_product_sync_odoo_id'), table_name='product_sync')
    op.drop_index(op.f('ix_product_sync_message'), table_name='product_sync')
    op.drop_index(op.f('ix_product_sync_instance_id'), table_name='product_sync')
    op.drop_index(op.f('ix_product_sync_id'), table_name='product_sync')
    op.drop_index(op.f('ix_product_sync_error_details'), table_name='product_sync')
    op.drop_table('product_sync')
    op.drop_index(op.f('ix_celery_task_logs_task_name'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_task_id'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_parent_task_id'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_instance_id'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_id'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_created_at'), table_name='celery_task_logs')
    op.drop_table('celery_task_logs')
    op.drop_index(op.f('ix_category_sync_woocommerce_id'), table_name='category_sync')
    op.drop_index(op.f('ix_category_sync_odoo_name'), table_name='category_sync')
    op.drop_index(op.f('ix_category_sync_odoo_id'), table_name='category_sync')
    op.drop_index(op.f('ix_category_sync_message'), table_name='category_sync')
    op.drop_index(op.f('ix_category_sync_instance_id'), table_name='category_sync')
    op.drop_index(op.f('ix_category_sync_id'), table_name='category_sync')
    op.drop_index(op.f('ix_category_sync_error_details'), table_name='category_sync')
    op.drop_table('category_sync')
    op.drop_index(op.f('ix_attribute_value_syncs_woocommerce_id'), table_name='attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_value_syncs_odoo_value_id'), table_name='attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_value_syncs_odoo_name'), table_name='attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_value_syncs_instance_id'), table_name='attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_value_syncs_id'), table_name='attribute_value_syncs')
    op.drop_table('attribute_value_syncs')
    op.drop_index(op.f('ix_attribute_syncs_woocommerce_id'), table_name='attribute_syncs')
    op.drop_index(op.f('ix_attribute_syncs_odoo_name'), table_name='attribute_syncs')
    op.drop_index(op.f('ix_attribute_syncs_odoo_attribute_id'), table_name='attribute_syncs')
    op.drop_index(op.f('ix_attribute_syncs_instance_id'), table_name='attribute_syncs')
    op.drop_index(op.f('ix_attribute_syncs_id'), table_name='attribute_syncs')
    op.drop_table('attribute_syncs')
    op.drop_index(op.f('ix_woocommerce_instances_user_id'), table_name='woocommerce_instances')
    op.drop_index(op.f('ix_woocommerce_instances_price_list_id'), table_name='woocommerce_instances')
    op.drop_index(op.f('ix_woocommerce_instances_name'), table_name='woocommerce_instances')
    op.drop_index(op.f('ix_woocommerce_instances_id'), table_name='woocommerce_instances')
    op.drop_table('woocommerce_instances')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_client_sync_id'), table_name='client_sync')
    op.drop_table('client_sync')
    op.drop_index(op.f('ix_admins_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_description'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
