"""
nuevo_cambio

Revision ID: 892afa9e3fc5
Revises: '89efc87892b4'
Create Date: 2026-02-06 18:11:23.045200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892afa9e3fc5'
down_revision: Union[str, None] = '89efc87892b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('uq_webhook_instance_topic_url', table_name='webhook_config')
    op.add_column('woocommerce_instances', sa.Column('product_descriptions', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('woocommerce_instances', 'product_descriptions')
    op.create_index('uq_webhook_instance_topic_url', 'webhook_config', ['instance_id', 'topic', 'delivery_url'], unique=True)
    # ### end Alembic commands ###
