"""
nuevo_cambio

Revision ID: 89efc87892b4
Revises: 'dfb9607acfcc'
Create Date: 2026-02-04 18:08:10.057855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89efc87892b4'
down_revision: Union[str, None] = 'dfb9607acfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelist_sync',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_pricelist_id', sa.Integer(), nullable=False, comment='Odoo pricelist ID'),
    sa.Column('odoo_pricelist_name', sa.String(length=255), nullable=True, comment='Odoo pricelist name'),
    sa.Column('instance_id', sa.Integer(), nullable=False, comment='WooCommerce instance ID'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Is this pricelist active for sync'),
    sa.Column('price_type', sa.String(length=50), nullable=False, comment='Type: regular, sale, meta'),
    sa.Column('meta_key', sa.String(length=100), nullable=True, comment='Meta key for custom price fields'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Last sync timestamp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True, comment='Last sync message or errors'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odoo_pricelist_id', 'instance_id', name='uq_pricelist_sync_instance')
    )
    op.create_index('idx_pricelist_sync_active', 'pricelist_sync', ['active'], unique=False)
    op.create_index('idx_pricelist_sync_instance', 'pricelist_sync', ['instance_id'], unique=False)
    # op.drop_index('uq_webhook_instance_topic_url', table_name='webhook_config')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_webhook_instance_topic_url', 'webhook_config', ['instance_id', 'topic', 'delivery_url'], unique=True)
    op.drop_index('idx_pricelist_sync_instance', table_name='pricelist_sync')
    op.drop_index('idx_pricelist_sync_active', table_name='pricelist_sync')
    op.drop_table('pricelist_sync')
    # ### end Alembic commands ###
