"""
remove_partida_posicion_unique_constraint

Revision ID: e8ebc767d0f7
Revises: '3c4e94de10eb'
Create Date: 2026-03-08 17:21:13.812172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ebc767d0f7'
down_revision: Union[str, None] = '3c4e94de10eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelist_sync',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_pricelist_id', sa.Integer(), nullable=False, comment='Odoo pricelist ID'),
    sa.Column('odoo_pricelist_name', sa.String(length=255), nullable=True, comment='Odoo pricelist name'),
    sa.Column('instance_id', sa.Integer(), nullable=False, comment='WooCommerce instance ID'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Is this pricelist active for sync'),
    sa.Column('price_type', sa.String(length=50), nullable=False, comment='Type: regular, sale, meta'),
    sa.Column('meta_key', sa.String(length=100), nullable=True, comment='Meta key for custom price fields'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Last sync timestamp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True, comment='Last sync message or errors'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odoo_pricelist_id', 'instance_id', name='uq_pricelist_sync_instance')
    )
    op.create_index('idx_pricelist_sync_active', 'pricelist_sync', ['active'], unique=False)
    op.create_index('idx_pricelist_sync_instance', 'pricelist_sync', ['instance_id'], unique=False)
    op.drop_constraint('attribute_syncs_ibfk_1', 'attribute_syncs', type_='foreignkey')
    op.create_foreign_key(None, 'attribute_syncs', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('attribute_value_syncs_ibfk_1', 'attribute_value_syncs', type_='foreignkey')
    op.create_foreign_key(None, 'attribute_value_syncs', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('category_sync_ibfk_1', 'category_sync', type_='foreignkey')
    op.create_foreign_key(None, 'category_sync', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('celery_task_logs_ibfk_1', 'celery_task_logs', type_='foreignkey')
    op.create_foreign_key(None, 'celery_task_logs', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_sync_ibfk_1', 'product_sync', type_='foreignkey')
    op.create_foreign_key(None, 'product_sync', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tag_sync_ibfk_1', 'tag_sync', type_='foreignkey')
    op.create_foreign_key(None, 'tag_sync', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('webhook_logs_ibfk_1', 'webhook_logs', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_logs', 'woocommerce_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'woocommerce_instances', 'pricelist_sync', ['price_list_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'woocommerce_instances', type_='foreignkey')
    op.drop_constraint(None, 'webhook_logs', type_='foreignkey')
    op.create_foreign_key('webhook_logs_ibfk_1', 'webhook_logs', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_constraint(None, 'tag_sync', type_='foreignkey')
    op.create_foreign_key('tag_sync_ibfk_1', 'tag_sync', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_constraint(None, 'product_sync', type_='foreignkey')
    op.create_foreign_key('product_sync_ibfk_1', 'product_sync', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_constraint(None, 'celery_task_logs', type_='foreignkey')
    op.create_foreign_key('celery_task_logs_ibfk_1', 'celery_task_logs', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_constraint(None, 'category_sync', type_='foreignkey')
    op.create_foreign_key('category_sync_ibfk_1', 'category_sync', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_constraint(None, 'attribute_value_syncs', type_='foreignkey')
    op.create_foreign_key('attribute_value_syncs_ibfk_1', 'attribute_value_syncs', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_constraint(None, 'attribute_syncs', type_='foreignkey')
    op.create_foreign_key('attribute_syncs_ibfk_1', 'attribute_syncs', 'woocommerce_instances', ['instance_id'], ['id'])
    op.drop_index('idx_pricelist_sync_instance', table_name='pricelist_sync')
    op.drop_index('idx_pricelist_sync_active', table_name='pricelist_sync')
    op.drop_table('pricelist_sync')
    # ### end Alembic commands ###
